name: Build and Release Flutter App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: actions/upload-artifact@v2
        with:
          name: ginx-windows
          path: build/windows/runner/Release/*.exe

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - uses: actions/upload-artifact@v2
        with:
          name: ginx-macos
          path: build/macos/Build/Products/Release/*.app

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          path: build/
      - uses: softprops/action-gh-release@v1
        with:
          files: build/**/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
