name: Build and Release Flutter App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # AdoptOpenJDK has been moved to Adoptium (Temurin)
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Update this to the version you're using
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: build/windows/runner/Release/*.exe

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Same change for macOS
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Ensure this matches your project's Flutter version
          channel: 'stable'
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app

  release:
    permissions:
      contents: write
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: build/
      - uses: softprops/action-gh-release@v1
        with:
          files: build/**/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}